name: 'Install Common Lisp Implementation'
description: 'Installs Common Lisp implementation and exposes it as LISP environment variable'
inputs:
  lisp:
    description: |
      Implementation to install:
        * sbcl - official package provided by SBCL developers
        * sbcl_ros - SBCL package provided by roswell maintainers
    required: true
    default: 'sbcl'
  version:
    description: 'Version of lisp implementation to install'
  install-prefix:
    description: |
      Path to install lisp implementation into.
    required: true
    default: "${{ github.workspace }}/.boroactions/lisp/v0/lisp/"
outputs:
  lisp:
    description: "Link to Common Lisp implementation executable"
    value: ${{ steps.output.lisp }}
runs:
  using: "composite"
  steps:
    - run: echo "LISP=$HOME/.local/bin/lisp" >> $GITHUB_ENV
      shell: sh
    - run: echo "LISP_INSTALL_PREFIX=$HOME/.local/opt/lisp/" >> $GITHUB_ENV
      shell: sh
    - run: ${{ github.action_path }}/install-lisp.sh "$LISP" ${{ inputs.lisp }} "$LISP_INSTALL_PREFIX" ${{ inputs.version }}
      shell: sh
    - id: output
      run: echo "::set-output name=lisp::$LISP"
      shell: sh
