name: 'Install Common Lisp Implementation'
description: 'Installs Common Lisp implementation and exposes it as LISP environment variable'
inputs:
  lisp:
    description: |
      Implementation to install:
        * sbcl - official package provided by SBCL developers
        * sbcl_ros - SBCL package provided by roswell maintainers
    required: true
    default: 'sbcl'
  version:
    description: 'Version of lisp implementation to install'
  install-prefix:
    description: |
      Path to install lisp implementation into.
    required: true
    default: "${{ github.workspace }}/.boroactions/lisp/v0/lisp/"
outputs:
  lisp:
    description: "Link to Common Lisp implementation executable"
    value: ${{ steps.output.outputs.lisp }}
runs:
  using: "composite"
  steps:
    - run: echo "LISP=$HOME/.local/bin/lisp" >> $GITHUB_ENV
      shell: sh
    - run: echo "LISP_INSTALL_PREFIX=${{ inputs.install-prefix }}/" >> $GITHUB_ENV
      shell: sh
    - id: lisp-id
      run: echo "::set-output name=value::$(${{ github.action_path }}/install-lisp.sh id --lisp ${{ inputs.lisp }} --version '${{ inputs.version }}')"
      shell: sh
    - run:
      shell: sh
    - id: cache
      uses: actions/cache@v2
      with:
        path: |
          ${{ env.LISP_INSTALL_PREFIX }}
        key: ${{ runner.os }}-${{ steps.lisp-id.outputs.value }}
    - run: ${{ github.action_path }}/install-lisp.sh install --lisp '${{ inputs.lisp }}' --version '${{ inputs.version }}' --bin "$LISP" --install-prefix "$LISP_INSTALL_PREFIX"
      shell: sh
    - id: output
      run: echo "::set-output name=lisp::$LISP"
      shell: sh
